---
kind: pipeline
type: kubernetes
name: terraform-aws-infra

clone:
  disable: true

steps:
  - name: clone-repo
    pull: if-not-exists
    image: smarthelios/git:1.0
    commands:
      - |
        touch hello.txt

  - name: clone-repo
    pull: never
    image: smarthelios/git:1.0
    commands:
      - |
        ls